version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.5
    - 13.1.6
  - dependency-name: react-map-gl
    versions:
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: mapbox-gl
    versions:
    - 2.0.1
    - 2.1.0
    - 2.1.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
